### ISSUE TITLE
Peer-to-peer review

### ISSUE THREAD

**Issue by Yonashenok** [lily4178993/To-do-list#4]
* UI look wonderful
* the code is clan well implemented
* the documentation is clear 
* Followed all the requirement 💯 
>
![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExOGQ0NjcxZmJiOTI5NDdiOTZkNGIzMWFmZjI0MThiYThjNWM5MmIzNCZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PWc/ytTYwIlbD1FBu/giphy.gif)

**Comment by lily4178993** [comment]
Thanks for all the reviews from this morning session.
Happy coding everyone!!!
